name: energy_optimized_beta_barrels
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - mdanalysis>=2.8
  - biopython
  - pytest
  - pip
  - pip:
      - pyrosetta-installer
